name: Docker Hub Retention

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  docker-hub-retention:
    runs-on: [ubuntu-latest]
    steps:
      - name: mailcatcher
        uses: philiplehmann/docker-hub-retention@v0.0.6
        with:
          repository: philiplehmann/mailcatcher
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          multiple: |
            - match: ([0-9\.]+)-([0-9]+)
              retention: 1m
            - match: build-cache.*
              retention: 14d
          # dryrun: "true"

      - name: maildev
        uses: philiplehmann/docker-hub-retention@v0.0.6
        with:
          repository: philiplehmann/maildev
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          multiple: |
            - match: ([0-9\.]+)-([0-9]+)
              retention: 1m
            - match: build-cache.*
              retention: 14d
          # dryrun: "true"

      - name: mailhog
        uses: philiplehmann/docker-hub-retention@v0.0.6
        with:
          repository: philiplehmann/mailhog
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          multiple: |
            - match: ([0-9\.]+)-([0-9]+)
              retention: 1m
            - match: build-cache.*
              retention: 14d
          # dryrun: "true"

      - name: pdftk
        uses: philiplehmann/docker-hub-retention@v0.0.6
        with:
          repository: philiplehmann/pdftk
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          multiple: |
            - match: ([0-9\.]+)-([0-9]+)
              retention: 1m
            - match: build-cache.*
              retention: 14d
          # dryrun: "true"

      - name: poppler
        uses: philiplehmann/docker-hub-retention@v0.0.6
        with:
          repository: philiplehmann/poppler-server
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          multiple: |
            - match: ([0-9\.]+)-([0-9]+)
              retention: 1m
            - match: build-cache.*
              retention: 14d
          # dryrun: "true"

      - name: puppeteer
        uses: philiplehmann/docker-hub-retention@v0.0.6
        with:
          repository: philiplehmann/puppeteer
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          multiple: |
            - match: ([0-9\.]+)-([0-9]+)
              retention: 1m
            - match: build-cache.*
              retention: 14d
          # dryrun: "true"

      - name: tesseract
        uses: philiplehmann/docker-hub-retention@v0.0.6
        with:
          repository: philiplehmann/tesseract
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          multiple: |
            - match: ([0-9\.]+)-([0-9]+)
              retention: 1m
            - match: build-cache.*
              retention: 14d
          # dryrun: "true"

      - name: unoserver
        uses: philiplehmann/docker-hub-retention@v0.0.6
        with:
          repository: philiplehmann/unoserver
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          multiple: |
            - match: ([0-9\.]+)-([0-9]+)
              retention: 1m
            - match: build-cache.*
              retention: 14d
          # dryrun: "true"
